In [29]:
import pandas as pd
import language_tool_python
import os

In [30]:
dir = "C:/Users/omara/OneDrive/Desktop/Erasmus University Rotterdam/MScBA Business Analytics Management/BMMTIBAM - Thesis & Internship/Data"
os.chdir(dir)

# Importing Data

In [31]:
data = pd.read_csv("experiment_grammar.csv")
data

,Unnamed: 0,ResponseId,Age,Gender,Ethnicity,Occupation,Years.of.Experience,Education,English_First_Language,GAI_Experience,...,Cloze3_2,Cloze3_3,Reward_Email,TimeTask1,TimeTask2,Text,GAIUsage,Spelling,ReadabilityFlesch,ReadabilityFleschKincaid
0,1,R_8Ugh2nEP1u6BVz0,2,2,Western European,1,3.0,5,0,2,...,1,1,v-lnooteboom@microsoft.com,678.051,744.891,"Dear all, As we are al living in troubled time...",0,1,68.379326,7.994744
1,2,R_8Ugh2nEP1u6BVz0,2,2,Western European,1,3.0,5,0,2,...,1,1,v-lnooteboom@microsoft.com,678.051,744.891,"Dear Team, As we stand on the cusp of closing...",1,0,44.422006,9.774453
2,3,R_6obwb8EpEihIXnj,1,2,South Asian,2,2.0,5,0,4,...,0,1,NaN,576.999,476.523,I lived in Rotterdam and made some amazing me...,0,5,80.870680,4.620672
3,4,R_6obwb8EpEihIXnj,1,2,South Asian,2,2.0,5,0,4,...,0,1,NaN,576.999,476.523,As we crossed the threshold into “La Panetter...,1,0,60.591830,9.147191
4,5,R_79t6G88l06sjyLM,1,1,Eastern European,2,1.0,7,1,5,...,1,0,t-ananegru@microsoft.com,687.969,736.418,"I consider my hometown to be special because,...",0,2,54.259375,12.988803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,100,R_4wDt7fkrnYxvopX,1,2,Northern European,1,1.0,3,0,4,...,1,1,daniel.eliassen@microsoft.com,547.203,674.711,"Stepping into “Le Jardin Secret,” warmth enve...",1,0,65.830288,7.664002
100,101,R_1KvWM289xSTDpQJ,3,2,Middle Eastern,1,23.0,7,0,5,...,1,1,NaN,597.125,622.512,"I grew up in Amman Amman is a large city, en...",0,2,53.048691,9.440384
101,102,R_1KvWM289xSTDpQJ,3,2,Middle Eastern,1,23.0,7,0,5,...,1,1,NaN,597.125,622.512,"As we step into the restaurant, the aroma of ...",1,1,57.938785,9.211330
102,103,R_523brMncKMoAHiu,2,1,Middle Eastern,1,6.0,5,1,4,...,1,1,rubba.ashwas@microsoft.com,566.283,763.995,"Hello, We are writing to announce a new wor...",0,1,58.843810,10.268783
103,104,R_523brMncKMoAHiu,2,1,Middle Eastern,1,6.0,5,1,4,...,1,1,rubba.ashwas@microsoft.com,566.283,763.995,"Dear Team, I hope this message finds you we...",1,0,49.424832,10.572268

# Creating Textual Characteristics (Experiment)

## Grammar

In [32]:
tool = language_tool_python.LanguageTool('en-US')

In [33]:
mistakes = []
for i in range(0, len(data)):
    text = data.loc[i, "Text"]
    matches = tool.check(text)
    matches = [match for match in matches if match.ruleId != 'MORFOLOGIK_RULE_EN_US']
    matches = [match for match in matches if match.ruleId != 'CONSECUTIVE_SPACES']
    matches = [match for match in matches if match.ruleId != 'WHITESPACE_RULE']
    mistakes.append(matches)
    data.loc[i, "Grammar"] = len(matches)

In [34]:
# Initialize an empty list to store the extracted information
mistakes_data = []

# Iterate over each sublist of mistakes
for sublist in mistakes:
    # Initialize an empty dictionary for each sublist
    sublist_data = {}
    # Extract information for each match in the sublist
    for match in sublist:
        # Extract relevant information from each match
        ruleId = match.ruleId
        message = match.message
        replacements = match.replacements
        offsetInContext = match.offsetInContext
        context = match.context
        offset = match.offset
        errorLength = match.errorLength
        category = match.category
        ruleIssueType = match.ruleIssueType
        sentence = match.sentence
        # Store the extracted information in a dictionary
        match_data = {
            'ruleId': ruleId,
            'message': message,
            'replacements': replacements,
            'offsetInContext': offsetInContext,
            'context': context,
            'offset': offset,
            'errorLength': errorLength,
            'category': category,
            'ruleIssueType': ruleIssueType,
            'sentence': sentence
        }
        # Append the match data to the sublist data
        sublist_data.update(match_data)
    # Append the sublist data to the overall list
    mistakes_data.append(sublist_data)

# Convert the list of dictionaries to a DataFrame
mistakes_df = pd.DataFrame(mistakes_data)

## Sentiment

In [35]:
from textblob import TextBlob

sentiment_scores = []

for i in range(0, len(data)):
    text = data.loc[i, "Text"]
    res = TextBlob(text)
    sentiment_scores.append(res.sentiment.polarity)
    data.loc[i, "Sentiment"] = res.sentiment.polarity

# Exporting

In [37]:
data.to_csv("experiment_grammar_sentiment.csv", index=False)

# Creating Textual Characteristics (Noy and Zhang)

In [39]:
data = pd.read_csv("data_grammar.csv")
data

,Unnamed: 0,responseid,comprehension1,comprehension2,empstat,tenure,skillranking_1,skillranking_2,skillranking_3,task_a_timespent_pagesubmit,...,chatgpt_often,task_a,task_b,usage,spellinga,spellingb,readabilityflescha,readabilityfleschb,readabilityfleschkincaida,readabilityfleschkincaidb
0,1,R_02RvSuhUUjDeDy9,1,1,2,20,1,2,3,30.430417,...,999,Potential benefits and risks of expanding oper...,Investing in research and development (R&D) fo...,1,0,2,64.990644,42.887439,7.383931,10.789647
1,4,R_0iZAhOXti4Rxp1n,1,1,999,20,1,3,2,19.767700,...,999,"Dear [Name],\r\n\r\nIt is my sincere pleasure ...","Dear [Name],\r\n\r\nMy purpose for writing you...",0,0,0,53.788828,40.285491,9.988421,12.475099
2,5,R_0iZuGqOYTtz9wFb,1,1,999,12,3,1,2,20.119550,...,999,"Good Afternoon Valued Employees,\r\n\r\nPlease...",Subject: Restructuring\r\n\r\nMy name is Sarah...,0,1,1,45.231629,50.017174,12.502786,10.754638
3,8,R_0qEA2U6SLtGyfYd,1,1,999,4,3,1,2,12.053000,...,3,Fitness is a very important aspect in our live...,I am writing to apply for a grant from your or...,1,0,0,68.741397,34.538047,7.036351,14.017789
4,9,R_0VgbTJtYjuUahcB,1,1,999,15,1,3,2,30.386917,...,4,Hello State of Minnesota\r\n\r\nThe City of Mi...,"Dear [Nonprofit],\r\n\r\nWe are writing to app...",1,2,0,28.088908,34.604619,16.311271,14.422550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,773,R_YQwEFctD2sQVdhT,1,1,1,15,1,2,3,29.687533,...,2,Hello everyone.\r\n\r\nWe have recently sent e...,A New Path Forward: Organizational Structure U...,1,0,1,61.045000,47.197202,9.713333,11.469462
365,775,R_yw14E1YBJZHmfFT,1,1,999,24,2,1,3,44.591467,...,2,As a management consultant working to help a U...,Investing in research and development (R&D) fo...,0,1,0,53.905400,45.759183,11.239896,11.213977
366,779,R_ZCXR2psutTYhp6h,1,1,999,5,2,3,1,15.782150,...,999,"Colleagues,\r\n\r\nAs you're aware, we've curr...","Colleagues,\r\n\r\nIt has come to our attentio...",0,2,0,46.698797,51.733504,11.819444,10.905631
367,780,R_ZfWqMLXoXIh1Qe5,1,1,999,8,1,2,3,18.544117,...,999,Subject: Funding for a Fun & Exciting Virtual ...,RE: AI Tutor Funding to Improve Performance Ga...,1,1,1,35.008525,49.039377,13.036848,11.074641
368,784,R_Zl60CRnGXjCxfzj,1,1,999,13,3,2,1,11.415917,...,2,The objective of this grant application is to ...,Oak Forest Middle School is excited at the pro...,0,1,1,28.380650,34.371957,15.606132,15.371424

## Grammar

In [40]:
mistakes = []
for i in range(0, len(data)):
    text = data.loc[i, "task_a"]
    matches = tool.check(text)
    matches = [match for match in matches if match.ruleId != 'MORFOLOGIK_RULE_EN_US']
    matches = [match for match in matches if match.ruleId != 'CONSECUTIVE_SPACES']
    matches = [match for match in matches if match.ruleId != 'WHITESPACE_RULE']
    mistakes.append(matches)
    data.loc[i, "grammar_a"] = len(matches)

mistakes = []
for i in range(0, len(data)):
    text = data.loc[i, "task_b"]
    matches = tool.check(text)
    matches = [match for match in matches if match.ruleId != 'MORFOLOGIK_RULE_EN_US']
    matches = [match for match in matches if match.ruleId != 'CONSECUTIVE_SPACES']
    matches = [match for match in matches if match.ruleId != 'WHITESPACE_RULE']
    mistakes.append(matches)
    data.loc[i, "grammar_b"] = len(matches)

In [41]:
# Initialize an empty list to store the extracted information
mistakes_data = []

# Iterate over each sublist of mistakes
for sublist in mistakes:
    # Initialize an empty dictionary for each sublist
    sublist_data = {}
    # Extract information for each match in the sublist
    for match in sublist:
        # Extract relevant information from each match
        ruleId = match.ruleId
        message = match.message
        replacements = match.replacements
        offsetInContext = match.offsetInContext
        context = match.context
        offset = match.offset
        errorLength = match.errorLength
        category = match.category
        ruleIssueType = match.ruleIssueType
        sentence = match.sentence
        # Store the extracted information in a dictionary
        match_data = {
            'ruleId': ruleId,
            'message': message,
            'replacements': replacements,
            'offsetInContext': offsetInContext,
            'context': context,
            'offset': offset,
            'errorLength': errorLength,
            'category': category,
            'ruleIssueType': ruleIssueType,
            'sentence': sentence
        }
        # Append the match data to the sublist data
        sublist_data.update(match_data)
    # Append the sublist data to the overall list
    mistakes_data.append(sublist_data)

# Convert the list of dictionaries to a DataFrame
mistakes_df = pd.DataFrame(mistakes_data)

## Sentiment

In [42]:
from textblob import TextBlob

sentiment_scores = []

for i in range(0, len(data)):
    text = data.loc[i, "task_a"]
    res = TextBlob(text)
    sentiment_scores.append(res.sentiment.polarity)
    data.loc[i, "sentiment_a"] = res.sentiment.polarity

sentiment_scores = []

for i in range(0, len(data)):
    text = data.loc[i, "task_b"]
    res = TextBlob(text)
    sentiment_scores.append(res.sentiment.polarity)
    data.loc[i, "sentiment_b"] = res.sentiment.polarity

# Export Data

In [43]:
data.to_csv("data_grammar_sentiment.csv", index=False)